### ISSUE TITLE
启用插件显示Server Error

### ISSUE THREAD

**Issue by KakuCicada** [Yves-X/Copyright-for-Typecho#3]
git clone 插件到typecho/usr/plugins下之后，在插件页面点击启动后，页面显示 Server Error
[https://ws4.sinaimg.cn/large/006tKfTcgy1fjzc3b3u7sj30lc064weg.jpg](url)
这个可能是什么问题导致的？

在nginx日志中，显示500请求
`GET /action/plugins-edit?activate=Copyright-for-Typecho&_=4f46962b1c6c114fddbd839dbd96f0c1 HTTP/1.1" 500 1061 "http://blog.xxxxxx.com/admin/plugins.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36" "-"`

typecho的版本是最新的开发版   b97289f7ebb341076008d88516ce2982ecc1b82e

**Comment by Yves-X** [comment]
插件没有在这个版本测试过。
请查看 php_error.log 的报错信息。

**Comment by JorenBai** [comment]
同样server error  更新了1.1

**Comment by tanluxiami** [comment]
这个问题的解决方法就是，进入plugins目录，将该插件文件夹重命名为Copyright即可，总之就是要保证typecho后台插件名称与该插件文件夹名称相同

**Comment by Yves-X** [comment]
谢谢反馈，已修复。
