### ISSUE TITLE
自定义字段设置无效

### ISSUE THREAD

**Issue by Tsuk1ko** [Yves-X/Copyright-for-Typecho#4]
目前是最新的 Typecho 1.1 正式版，想用自定义字段的时候发现自定义字段无效。  
不知道是不是新版 Typecho 的锅，因为以前用 1.0 的时候没有试过自定义字段。    
想询问下您是否有遇到这个问题，谢谢。

**Comment by Tsuk1ko** [comment]
解决了，只要编辑插件，将其中获取自定义字段时的`isset`函数去掉就可以了。  
应该是 Typecho 1.1 更改了自定义字段获取的逻辑，如果字段没有设置，返回的是一个空字符串而不是`NULL`。

**Comment by Tsuk1ko** [comment]
呃，说漏了，不仅要去掉`isset`，还要加个`!=""`

**Comment by Yves-X** [comment]
谢谢反馈与您的修复。
