### ISSUE TITLE
开启 DigestShow 插件，会导致 Copyright-for-Typecho 不显示

### ISSUE THREAD

**Issue by cppfuns** [Yves-X/Copyright-for-Typecho#5]
RT

**Comment by Yves-X** [comment]
抱歉没有更及时地回应。

刚刚解决了这类问题：[81743d8](https://github.com/Yves-X/Copyright-for-Typecho/commit/81743d86a5870ff105e52726e3a6b67317fcf903)
你可以参照上面的 commit 或者更新一下。

插件需要重新启动一次，请记得全局设置需要重新配置。

**Comment by cppfuns** [comment]
@Yves-X 
已更新，并重新启动设置了插件，还是不显示，测试页面如下
https://www.bcskill.com/index.php/archives/111.html

**Comment by Yves-X** [comment]
@cppfuns 
您能够确定该问题仅与 DigestShow 插件相关吗？
您是否在使用旧版本 Typecho？

**Comment by cppfuns** [comment]
确定与DigestShow有关，在无任何干扰条件下，开启此插件，Copyright将不显示，关闭后，一切正常。
Typecho 代码，用的https://github.com/typecho/typecho.git 此时最新 master 分支

**Comment by Yves-X** [comment]
Typecho 1.1 (17.12.8)
Copyright-for-Typecho 1.0.2
DigestShow 1.1.0

没有能够复现你的情况。

**Comment by cppfuns** [comment]
会不会是 typecho 更新导致的，
我用的https://github.com/typecho/typecho.git 此时最新 master 分支
不过 即使是更新导致的，因为 typecho 在 Typecho 1.1 (17.12.8) 更新了很多，还是希望能兼容更新下。

**Comment by Yves-X** [comment]
git pull 到现在 master 的最新代码，版本显示为 1.2 (18.1.29)。
尝试了两个插件先后启动的两种顺序，依然没有复现你的情况，可以提供一下您正在使用的 DigestShow 吗？

**Comment by cppfuns** [comment]
[Plugin.zip](https://github.com/Yves-X/Copyright-for-Typecho/files/2131540/Plugin.zip)

**Comment by Yves-X** [comment]
DigestShow 没有考虑到这个问题，它会干扰同一位置修改内容的其他函数的工作。这不是本插件的问题，例如，如果它用于 content 接口，那么同样会干扰 markdown 渲染器。
你需要修改一下 DigestShow 的 Plugin.php：
给 `render` 函数加一个参数 `$lastResult`，在函数开头添一句 `$content = empty($lastResult) ? $content : $lastResult;`

即
```
    public static function render($content, $thisObj, $lastResult){
		$content = empty($lastResult) ? $content : $lastResult;

		$typelist = array(
```
后面略

**Comment by cppfuns** [comment]
666 问题棒棒的解决了，感谢~

**Comment by Yves-X** [comment]
@cppfuns 不客气 :)
